// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBfszJ4v5ynPDsz7eOZVRyDCIDmlNURg0s',
    appId: '1:1080593140360:web:9c6091401bace303a16d3d',
    messagingSenderId: '1080593140360',
    projectId: 'ditonton-ziyad',
    authDomain: 'ditonton-ziyad.firebaseapp.com',
    storageBucket: 'ditonton-ziyad.appspot.com',
    measurementId: 'G-2HKJFRG9WP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBUs1buVH1pKWGUDdOmrDV7LJSR03WAxNM',
    appId: '1:1080593140360:android:2b507026b3ad438ca16d3d',
    messagingSenderId: '1080593140360',
    projectId: 'ditonton-ziyad',
    storageBucket: 'ditonton-ziyad.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBG3tDU4YUpGjmZMej11RGrKLjru0v4Anw',
    appId: '1:1080593140360:ios:a2b61478eac10ea8a16d3d',
    messagingSenderId: '1080593140360',
    projectId: 'ditonton-ziyad',
    storageBucket: 'ditonton-ziyad.appspot.com',
    iosClientId: '1080593140360-1do5cclpaprjn39o9objar9govsgi9da.apps.googleusercontent.com',
    iosBundleId: 'com.dicoding.ditonton',
  );
}
